// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolve } from "path";

// Fallback pour DATABASE_URL si non défini
if (!process.env.DATABASE_URL) {
  const dbPath = resolve(process.cwd(), "dev.db");
  process.env.DATABASE_URL = `file:${dbPath}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
